//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMSE.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NMSE.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About &quot;Markov Patient Journey Modelling&quot;.
        /// </summary>
        public static string AboutPageTitle {
            get {
                return ResourceManager.GetString("AboutPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markov Patient Journey Modelling.
        /// </summary>
        public static string AppDisplayName {
            get {
                return ResourceManager.GetString("AppDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disease specific patient flow data (rates and transitions).
        /// </summary>
        public static string Data1PageTitle {
            get {
                return ResourceManager.GetString("Data1PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time relations of patient journey.
        /// </summary>
        public static string Data2PageTitle {
            get {
                return ResourceManager.GetString("Data2PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interventions to improve patient journey.
        /// </summary>
        public static string Data3PageTitle {
            get {
                return ResourceManager.GetString("Data3PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interventions.
        /// </summary>
        public static string InterventionsPageTitle {
            get {
                return ResourceManager.GetString("InterventionsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Settings.
        /// </summary>
        public static string OutputSettingsPageTitle {
            get {
                return ResourceManager.GetString("OutputSettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Description.
        /// </summary>
        public static string ProjectDescriptionPageTitle {
            get {
                return ResourceManager.GetString("ProjectDescriptionPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Simulation.
        /// </summary>
        public static string RunSimulationPageTitle {
            get {
                return ResourceManager.GetString("RunSimulationPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Model Type.
        /// </summary>
        public static string SelectModelPageTitle {
            get {
                return ResourceManager.GetString("SelectModelPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings page placeholder text.  Your app description goes here..
        /// </summary>
        public static string SettingsPageAboutText {
            get {
                return ResourceManager.GetString("SettingsPageAboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About this application.
        /// </summary>
        public static string SettingsPageAboutTitle {
            get {
                return ResourceManager.GetString("SettingsPageAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Theme.
        /// </summary>
        public static string SettingsPageChooseThemeText {
            get {
                return ResourceManager.GetString("SettingsPageChooseThemeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalization.
        /// </summary>
        public static string SettingsPagePersonalizationTitle {
            get {
                return ResourceManager.GetString("SettingsPagePersonalizationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Statement.
        /// </summary>
        public static string SettingsPagePrivacyStatementText {
            get {
                return ResourceManager.GetString("SettingsPagePrivacyStatementText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string SettingsPageRadioButtonDarkTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string SettingsPageRadioButtonLightTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonLightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string SettingsPageRadioButtonWindowsDefaultTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonWindowsDefaultTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Settings.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetupCheck.
        /// </summary>
        public static string SetupCheckPageTitle {
            get {
                return ResourceManager.GetString("SetupCheckPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string ShellAboutPage {
            get {
                return ResourceManager.GetString("ShellAboutPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup Patient Flow.
        /// </summary>
        public static string ShellData1Page {
            get {
                return ResourceManager.GetString("ShellData1Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup Time Relations.
        /// </summary>
        public static string ShellData2Page {
            get {
                return ResourceManager.GetString("ShellData2Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup Interventions.
        /// </summary>
        public static string ShellData3Page {
            get {
                return ResourceManager.GetString("ShellData3Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back.
        /// </summary>
        public static string ShellGoBackButton {
            get {
                return ResourceManager.GetString("ShellGoBackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open or close navigation.
        /// </summary>
        public static string ShellHamburgerButtonName {
            get {
                return ResourceManager.GetString("ShellHamburgerButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interventions.
        /// </summary>
        public static string ShellInterventionsPage {
            get {
                return ResourceManager.GetString("ShellInterventionsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Settings.
        /// </summary>
        public static string ShellOutputSettingsPage {
            get {
                return ResourceManager.GetString("ShellOutputSettingsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Description.
        /// </summary>
        public static string ShellProjectDescriptionPage {
            get {
                return ResourceManager.GetString("ShellProjectDescriptionPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Simulation.
        /// </summary>
        public static string ShellRunSimulationPage {
            get {
                return ResourceManager.GetString("ShellRunSimulationPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Model.
        /// </summary>
        public static string ShellSelectModelPage {
            get {
                return ResourceManager.GetString("ShellSelectModelPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string ShellSettingsPage {
            get {
                return ResourceManager.GetString("ShellSettingsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup Check.
        /// </summary>
        public static string ShellSetupCheckPage {
            get {
                return ResourceManager.GetString("ShellSetupCheckPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulation Properties.
        /// </summary>
        public static string ShellSimulationPropertiesPage {
            get {
                return ResourceManager.GetString("ShellSimulationPropertiesPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulation Results.
        /// </summary>
        public static string ShellSimulationResultsPage {
            get {
                return ResourceManager.GetString("ShellSimulationResultsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Manual.
        /// </summary>
        public static string ShellUserManualPage {
            get {
                return ResourceManager.GetString("ShellUserManualPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulation Properties.
        /// </summary>
        public static string SimulationPropertiesPageTitle {
            get {
                return ResourceManager.GetString("SimulationPropertiesPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulation Results.
        /// </summary>
        public static string SimulationResultsPageTitle {
            get {
                return ResourceManager.GetString("SimulationResultsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Manual.
        /// </summary>
        public static string UserManualPageTitle {
            get {
                return ResourceManager.GetString("UserManualPageTitle", resourceCulture);
            }
        }
    }
}
